config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'films#index'

  get "/detalle", to: "films#show", as: "film"

  get "/personaje", to: "films#personaje", as: "personaje"

  get "/planeta", to: "films#planeta", as: "planeta"

  get "/nave", to: "films#nave", as: "nave"

  get "/search", to: "films#search", as: "search"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class SwApi
	include HTTParty

	def films
		self.class.get('https://swapi.co/api/films')
	end

	def people
		self.class.get('swapi.co/api/people')
	end

	def planets
		self.class.get('swapi.co/api/planets')
	end

	def starships	
		self.class.get('swapi.co/api/starships')
	end

	def people_by_link(link)
		self.class.get(link)
	end

end

class FilmsController < ApplicationController
	def index
		swap = SwApi.new
		@films = swap.films();
	end

	def show
		swap = SwApi.new
		@film = swap.people_by_link(params[:pelicula])
		@characters = Array.new
		@film['characters'].each do |char|
			@characters.insert(-1,swap.people_by_link(char))
		end
		@planetas = Array.new
		@film['planets'].each do |planet|
			@planetas.insert(-1, swap.people_by_link(planet))
		end

		@naves = Array.new
		@film['starships'].each do |nave|
			@naves.insert(-1, swap.people_by_link(nave))
		end

	end

	def personaje
		swap = SwApi.new
		@personaje = swap.people_by_link(params[:url])
		@films = Array.new

		@planet = swap.people_by_link(@personaje["homeworld"])

		@personaje['films'].each do |film|
			@films.insert(-1, swap.people_by_link(film))
		end

		@naves = Array.new
		@personaje['starships'].each do |nave|
			@naves.insert(-1, swap.people_by_link(nave))
		end
	end

	def planeta
		swap = SwApi.new
		@planeta = swap.people_by_link(params[:url])
		
		@characters = Array.new
		@planeta['residents'].each do |char|
			@characters.insert(-1,swap.people_by_link(char))
		end

		@films = Array.new
		@planeta['films'].each do |film|
			@films.insert(-1, swap.people_by_link(film))
		end

	end

	def nave
		swap =  SwApi.new
		@nave = swap.people_by_link(params[:url])

		@characters = Array.new
		@nave['pilots'].each do |char|
			@characters.insert(-1,swap.people_by_link(char))
		end
		@films = Array.new
		@nave['films'].each do |film|
			@films.insert(-1, swap.people_by_link(film))
		end

	end

	def search
		swap. SwApi.new
		@films = swap.people_by_link('https://swapi.co/api/films/?search='+ params[:busqueda]) ['results']
		@naves = swap.people_by_link('https://swapi.co/api/starships/?search='+ params[:busqueda])['results']
		@characters = swap.people_by_link('https://swapi.co/api/people/?search=' + params[:busqueda])['results']
		@planetas = swap.people_by_link('https://swapi.co/api/planets/?search=' + params[:busqueda])['results']

	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/index.html.erb
<h1>Peliculas</h1>


<% @films['results'].each do |film| %>
<h2> <%= link_to film['title'], film_path(:pelicula => film['url']) %> </h2>
<p> Fecha de Lanzamiento = <%= film['release_date']%> </p>
<p> director = <%= film['director']%> , productores: <%= film['producer']%> , Episodio n° <%= film['episode_id']%> </p>
	

<% end %>

app/views/films/nave.html.erb
<h1> <%= @nave['name'] %> </h1>

<p> Modelo : <%=@nave['model'] %>,
Constructor: <%=@nave['manufacturer'] %>,
Costo en creditos: <%=@nave['cost_in_credits'] %>,
Largo :<%=@nave['length'] %>,
Maxima velocidad Atmosferica: <%=@nave['max_atmosphering_speed'] %>,
Tripulacion: <%=@nave['crew'] %>,
pasajeros: <%=@nave['passengers'] %>,
Capacidad de Carga: <%=@nave['cargo_capacity'] %>,
Consumibles:<%=@nave['consumables'] %> ,
Velocidad del ultrasonido?: <%=@nave['hyperdrive_rating'] %>,
MLGT: <%=@nave['MGLT'] %>,
Clase: <%=@nave['starship_class'] %>,
</p>
<h2> Pilotos</h2>
<p><% @characters.each do |char|%> <%= link_to char['name'] , personaje_path(:url => char['url'])%> , <%end %></p>
<h2> Peliculas </h2>
<p> <% @films.each do |film|%> <%= link_to film['title'] , film_path(:pelicula => film['url'])%>, <% end %></p>

app/views/films/personaje.html.erb
<h1> <%= @personaje["name"] %> </h1>
<h2> Datos Generales </h2>
<p> Año de Nacimiento: <%= @personaje['birth_year'] %> , Color de los Ojos: <%= @personaje['eye_color'] %>, sexo: <%= @personaje['gender'] %>, color del pelo: <%= @personaje['hair_color'] %>, Altura: <%= @personaje['height'] %>, peso: <%= @personaje['mass'] %>, color de piel: <%= @personaje['skin_color'] %>, planeta Origen : <%= link_to @planet['name'] , planeta_path(:url => @planet['url']) %> </p>
<h2> Peliculas En las que aparece</h2>

<p> <% @films.each do |film|%> <%= link_to film['title'] , film_path(:pelicula => film['url'])%>, <% end %></p>

<h2> Naves </h2>

<p><% @naves.each do |nave|%> <%= link_to nave['name'] , nave_path(:url => nave['url'])%> , <%end %></p>

app/views/films/planeta.html.erb
<h1> <%= @planeta["name"] %> </h1>

<p> Periodo de Rotacion: <%= @planeta['rotation_period'] %> , 
Periodo de traslación : <%= @planeta['orbital_period']%>,
Diametro : <%= @planeta['diameter']%>,
Clima : <%= @planeta['climate']%>,
Gravedad: <%= @planeta['gravity']%>,
terreno: <%= @planeta['terrain']%>,
Agua en la superficie : <%= @planeta['surface_water']%>,
Poblacion : <%= @planeta['population']%>.
 </p>

 <h2> Residentes </h2>

 <p><% @characters.each do |char|%> <%= link_to char['name'] , personaje_path(:url => char['url'])%> , <%end %></p>

<h2> Peliculas </h2>

<p> <% @films.each do |film|%> <%= link_to film['title'] , film_path(:pelicula => film['url'])%>, <% end %></p>

app/views/films/search.html.erb
<h1> Resultado Busqueda</h1>

<h2> Peliculas </h2>

<p> <% @films.each do |film|%> <%= link_to film['title'] , film_path(:pelicula => film['url'])%>, <% end %></p>

<h2> Personajes </h2>

<p><% @characters.each do |char|%> <%= link_to char['name'] , personaje_path(:url => char['url'])%> , <%end %></p>

<h2> Planetas </h2>

<p><% @planetas.each do |planeta|%> <%= link_to planeta['name'] , planeta_path(:url => planeta['url'])%> , <%end %></p>

<h2> Naves </h2>

<p><% @naves.each do |nave|%> <%= link_to nave['name'] , nave_path(:url => nave['url'])%> , <%end %></p>

app/views/films/show.html.erb
# encoding: utf-8
<h1> <%= @film['title'] %> </h1>
<h2> Datos Generales </h2>
<p> Director: <%= @film['director']%>, Fecha de Lanzamiento: <%= @film['release_date']%>, Episodio N°<%= @film['episode_id']%>, Productores : <%= @film['producer']%></p>
<p> <%= @film['opening_crawl']%></p>

<h2> Personajes</h2>

<p><% @characters.each do |char|%> <%= link_to char['name'] , personaje_path(:url => char['url'])%> , <%end %></p>

<h2> Planetas </h2>

<p><% @planetas.each do |planeta|%> <%= link_to planeta['name'] , planeta_path(:url => planeta['url'])%> , <%end %></p>

<h2> Naves </h2>

<p><% @naves.each do |nave|%> <%= link_to nave['name'] , nave_path(:url => nave['url'])%> , <%end %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swapiti</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">

    </div>
  </nav>
</header>

    <%= yield %>
  </body>
</html>